version: '3.8'
services:
  tr-central-server:
    image: niis/xroad-central-server
    extra_hosts:
      - "central.xroad.gov.tr:10.6.7.214"
    ports:
      - "3052:80"
      - "3053:4000"
      - "3054:4001"
      - "3055:4002"
      - "3056:8888"
      - "3057:8889"

  tr-security-server:
    image: niis/xroad-security-server
    environment:
      - XROAD_TOKEN_PIN="1234"
    ports:
      - "3058:4000"
      - "3059:8080"

  # uz-central-server:
  #   image: niis/xroad-central-server
  #   ports:
  #     - "3062:80"
  #     - "3063:4000"
  #     - "3064:4001"
  #     - "3065:4002"
  #     - "3066:8888"
  #     - "3067:8889"

  # uz-security-server:
  #   image: niis/xroad-security-server
  #   environment:
  #     - XROAD_TOKEN_PIN="1234"
  #   ports:
  #     - "3068:4000"
  #     - "3069:8080"
